{%- raw -%}
{% set data = load_setup_py_data() %}
{%- endraw %}

package:
  name: conda-build-test-source-setup-py-data
  {%- raw %}
  version: {{ data.get('version') }}
  {%- endraw %}

source:
  path_url: ../

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python

  run:
    - python
  {% for package in pkg.requires %}
    - {{ package }}
  {% endfor %}

test:
  requires:
    - pytest

  imports:
    - {{pkg.pkgimp}}

about:
  description: {{pkg.description}}
  author: {{pkg.author}}
